"""create tables

Revision ID: 42bf83e0ee1c
Revises: 
Create Date: 2023-01-14 20:46:09.919065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42bf83e0ee1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anketa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest1', sa.String(length=200), nullable=True),
    sa.Column('quest2', sa.String(length=200), nullable=True),
    sa.Column('quest3', sa.String(length=200), nullable=True),
    sa.Column('quest4', sa.String(length=200), nullable=True),
    sa.Column('quest5', sa.String(length=200), nullable=True),
    sa.Column('quest6', sa.String(length=200), nullable=True),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=120), nullable=True),
    sa.Column('activity', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('anketa')
    # ### end Alembic commands ###
